/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//1. Directivas de preporocesamiento
#include <stdint.h>
#include <stdio.h>

//2. Otras directivas de preprocesamiento
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//3. Variables de la clase
uint32_t workingDays = 0;			//Variable definida
uint32_t numberOfDoors = 0;	//Variable definida e inicializada, por buenas prácticas, siempre cada variable que definimos se le debe dar un valor inicial

//4. Prototipos de las funciones privadas
void ejemploCicloFor(void){
	for(uint8_t i = 0; i < 32; i++){ //Soy un ciclo for :D
		numberOfDoors = i;
	}
}
void bloqueIfElse(){
	uint8_t auxValue = 45;
	if(auxValue == 45){
		/* Si la condición es 0, significa que el interior del if no se ejecuta, de lo contrario,
		 * se ejecuta lo que esta dentro de las llaves del if*/
		//No pues, que pase alguna vaina
	}
}
void numerosPares(void){
	for(uint8_t counter = 0; counter < 100; counter++){
		if(counter%2 == 0){
			// imprimir el número
			//Tarea, hacer una función que nos imprima los números primos hasta el 1000
		}
	}
}


//5. Funciones
int main(void)
{
    /* Loop forever */
	for(;;);
}
